# Generated by Django 3.1.7 on 2021-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('HotelName', models.TextField()),
                ('HotelAddress', models.TextField()),
                ('HotelRating', models.FloatField()),
                ('ReviewDate', models.TextField()),
                ('ReviewRating', models.FloatField()),
                ('ReviewTitle', models.TextField()),
                ('ReviewText', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rawfile')),
            ],
        ),
    ]
