# Generated by Django 3.1.7 on 2021-04-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData_17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryData_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultData_8',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.TextField()),
                ('sentiment', models.BooleanField()),
                ('rawid', models.ForeignKey(db_column='rawid', on_delete=django.db.models.deletion.CASCADE, to='nlp_proj.rawdata')),
            ],
        ),
        migrations.CreateModel(
            name='ResultData_17',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.TextField()),
                ('sentiment', models.BooleanField()),
                ('rawid', models.ForeignKey(db_column='rawid', on_delete=django.db.models.deletion.CASCADE, to='nlp_proj.rawdata')),
            ],
        ),
    ]
