# Generated by Django 3.1.7 on 2021-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0002_categorydata_17_categorydata_8_resultdata_17_resultdata_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultdata_17',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultdata_8',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
