# Generated by Django 3.1.7 on 2021-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0003_auto_20210401_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdata_17',
            name='rawid',
        ),
        migrations.RemoveField(
            model_name='resultdata_8',
            name='rawid',
        ),
        migrations.AddField(
            model_name='resultdata_17',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultdata_17',
            name='raw_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultdata_8',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultdata_8',
            name='raw_text',
            field=models.TextField(default=''),
        ),
    ]
