# Generated by Django 3.1.7 on 2021-04-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0006_auto_20210401_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
